server:
  port: 8000
spring:
  application:
    name: microservice-provider-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://user:passwork123@localhost:8761/eureka/
#      defaultZone: http://peer1:8761/eureka,http://peer2:8761/eureka
  instance:
    prefer-ip-address: true
    metadata-map:
      my-metadata: 海阔凭鱼跃，天高任鸟飞。

logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
management:
  security:
    enabled: false


#info:
#  app:
#    name: @project.artifactId@
#    encoding: @project.build.sourceEnCoding@
#    java:
#      source: @java.version@
#      target: @java.version@
info:
  app:
    name: guanth
    encoding: UTF-8
    java:
      source: 1.8
      target: 1.8